/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
        "boost.browser-logs": [],
        "welcome": [],
        "homepage": [],
        "myprofile": [],
        "dashboard": [],
        "kategori": [],
        "kategori.add": [],
        "kategori.update": [
            {
                "name": "kategori",
                "required": true,
                "binding": "id"
            }
        ],
        "kategori.delete": [
            {
                "name": "kategori",
                "required": true,
                "binding": "id"
            }
        ],
        "kelola_produk": [],
        "myoutlet": [],
        "myoutlet.add": [],
        "myoutlet.update": [
            {
                "name": "outlet",
                "required": true,
                "binding": "id"
            }
        ],
        "myoutlet.delete": [
            {
                "name": "outlet",
                "required": true,
                "binding": "id"
            }
        ],
        "produk": [
            {
                "name": "outlet_id",
                "required": true
            }
        ],
        "produk.add": [],
        "produk.update": [
            {
                "name": "produk",
                "required": true,
                "binding": "id"
            }
        ],
        "produk.delete": [
            {
                "name": "produk",
                "required": true,
                "binding": "id"
            }
        ],
        "req_staff": [],
        "req_staff.add": [],
        "add_staff": [
            {
                "name": "outlet_id",
                "required": true
            }
        ],
        "terima_staff": [
            {
                "name": "id",
                "required": true
            }
        ],
        "tolak_staff": [
            {
                "name": "id",
                "required": true
            }
        ],
        "profile.edit": [],
        "profile.update": [],
        "profile.destroy": [],
        "appearance.edit": [],
        "login": [],
        "logout": [],
        "storage.local": [
            {
                "name": "path",
                "required": true
            }
        ],
        "storage.local.upload": [
            {
                "name": "path",
                "required": true
            }
        ]
    }
}
import type { route as ZiggyRoute } from 'ziggy-js';
declare global {
  const route: typeof ZiggyRoute;
}

export {};
